### ISSUE TITLE
getTZoffset() method passes wrong arguments to Java method

### ISSUE THREAD

**Issue by sebduggan** [coldbox-modules/cbox-i18n#26]
The method `getTZoffset()` takes the wrong argument, and passes the wrong argument to the Java `getOffset()` method.

Currently, it passes through an offset value. However, the `getOffset()` method takes a date as an argument - the date for which the offset needs calculating - as a date value in milliseconds.

(Where `getOffset()` is called in `i18nDateDiff()`, it is called correctly).

**Comment by lmajano** [comment]
Do you have an example or pull request so I can include it?

**Comment by sebduggan** [comment]
PR #27 created...

**Comment by lmajano** [comment]
Thank you so much kind sir!
